# Generated by Django 5.2 on 2025-09-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.TextField(),
        ),
    ]
