# Generated by Django 5.2 on 2025-09-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_alter_run_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('in_progress', 'In_progress'), ('finished', 'Finished')], default='init'),
        ),
    ]
