# Generated by Django 5.2 on 2025-09-25 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_run_status'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='athlete_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('goals', models.TextField()),
                ('weight', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
