# Generated by Django 5.2 on 2025-09-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_alter_athleteinfo_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
