# Generated by Django 5.2 on 2025-09-26 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='athlete',
            new_name='user',
        ),
    ]
