# Generated by Django 5.2 on 2025-09-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_rename_user_athleteinfo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user_id',
            new_name='athlete',
        ),
    ]
