# Generated by Django 5.2 on 2025-10-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0020_alter_position_latitude_alter_position_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
