# Generated by Django 5.2 on 2025-10-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0022_position_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
