# Generated by Django 5.2 on 2025-10-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0023_position_distance_position_speed_run_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
