# Generated by Django 5.2 on 2025-10-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0024_alter_position_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
