# Generated by Django 5.2 on 2025-10-15 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0026_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='raiting',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
