# Generated by Django 5.2 on 2025-10-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0027_subscribe_raiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='raiting',
            new_name='rating',
        ),
    ]
